### ISSUE TITLE
Memcache issues

### ISSUE THREAD

**Issue by paulcanning** [ivantcholakov/starter-public-edition-3#2]
After running a non-HMVC script, a memcache folder and file is created, and then a subsequent reload gives me an error saying it cannot find the memcache file.

How do i disable memcache?

**Comment by ivantcholakov** [comment]
I have never tried  memcache. Could you give me more details what happens?

**Comment by paulcanning** [comment]
Thats all the details I have. I downloaded the repo and tried out the demo.php from the non-HMVC stuff. It created a memcache folder inside the folder where demo.php was.

**Comment by ivantcholakov** [comment]
Ok, I will test soon.

**Comment by ivantcholakov** [comment]
Literally, what is the name of the newly created folder?

**Comment by paulcanning** [comment]
Memcache

**Comment by ivantcholakov** [comment]
I have just checked the whole source, there is no code that is to create a directory with this specific name. External code probably does that, it is up to you to find it.

**Comment by paulcanning** [comment]
This wasn't happening till I added in this repo :/

**Comment by ivantcholakov** [comment]
I am sorry, but I can not identify a problem to be addressed to me. I am closing this issue.
